'use client';
import {Canvas,useFrame} from '@react-three/fiber'; import {ContactShadows,Float,Html,OrbitControls,PerspectiveCamera,Stars} from '@react-three/drei'; import {EffectComposer,Bloom,Noise,Vignette} from '@react-three/postprocessing'; import {useRef} from 'react'; import * as THREE from 'three';
function Camera(){const r=useRef<THREE.Group>(null!);useFrame(({camera})=>{const p=Math.min(scrollY/(document.body.scrollHeight-innerHeight),1); camera.position.lerp(new THREE.Vector3(p*2.8,p>.7?2.8:2.2,9-p*3.4),.035);camera.lookAt(p*1.2,.2,0);if(r.current)r.current.rotation.y=Math.sin(p*5)*.05});return <group ref={r}/>}
function Label({children,position}:{children:React.ReactNode,position:[number,number,number]}){return <Html position={position} center distanceFactor={10}><span className="three-label">↗ {children}</span></Html>}
function Laptop({onClick}:{onClick:()=>void}){return <group position={[1.7,.15,.2]} rotation={[0,-.35,0]}><mesh position={[0,1.1,0]} onClick={onClick}><boxGeometry args={[2.7,1.65,.16]}/><meshStandardMaterial color="#152229" metalness={.9} roughness={.25} emissive="#12333a" emissiveIntensity={.5}/></mesh><mesh position={[0,1.1,.1]} onClick={onClick}><planeGeometry args={[2.32,1.29]}/><meshBasicMaterial color="#06191b"/><Html transform position={[0,1.1,.11]} distanceFactor={1.65}><div className="terminal" onClick={onClick}>const maker = {'{'}<br/>device: <b>&apos;Android&apos;</b>,<br/>tool: <b>&apos;Termux&apos;</b>,<br/>limit: <b>null</b>{'}'}</div></Html></mesh><mesh position={[0,.22,.7]} rotation={[-.18,0,0]}><boxGeometry args={[2.95,.12,1.8]}/><meshStandardMaterial color="#26302d" metalness={1}/></mesh><Label position={[0,2.1,0]}>CLICK / PROJECT UNIVERSE</Label></group>}
function Phone(){return <Float speed={2} rotationIntensity={.25} floatIntensity={.3}><group position={[-1.1,.55,1.2]} rotation={[.1,.25,.13]}><mesh><boxGeometry args={[.68,1.45,.13]}/><meshStandardMaterial color="#171e20" metalness={.8}/></mesh><mesh position={[0,0,.075]}><planeGeometry args={[.51,1.12]}/><meshBasicMaterial color="#061209"/><Html transform position={[0,0,.08]} distanceFactor={1.6}><div className="termux">TERMUX<br/>$ npm run build<br/><b>✓ optimized</b><br/>$ git push<br/><b>✓ deployed</b></div></Html></mesh><Label position={[.8,.55,0]}>ANDROID WORKFLOW</Label></group></Float>}
function Notebook(){return <group position={[-2.5,.26,.2]} rotation={[-.1,.15,-.18]}><mesh><boxGeometry args={[1.65,.1,1.12]}/><meshStandardMaterial color="#aaa58e" roughness={.8}/></mesh><Html transform position={[0,.065,0]} rotation={[-Math.PI/2,0,0]} distanceFactor={1.2}><div className="note">BLUEPRINT / 01<br/><i>creativity isn&apos;t<br/>limited by hardware.</i></div></Html><Label position={[0,.65,0]}>ABOUT / BLUEPRINT</Label></group>}
function Hologram(){return <Float speed={1.5} floatIntensity={.8}><group position={[3.4,1.8,-.7]}><mesh><icosahedronGeometry args={[.58,1]}/><meshStandardMaterial color="#73e8ff" wireframe emissive="#167a90" emissiveIntensity={1}/></mesh><pointLight color="#69eaff" intensity={3} distance={4}/><Label position={[0,.9,0]}>OPEN SOURCE</Label></group></Float>}
function Skills(){return <group position={[-.2,2.3,-1.3]}>{['REACT','NEXT.JS','GLSL'].map((x,i)=><Float key={x} speed={1+i} position={[Math.cos(i*2.1)*1.35,Math.sin(i*2.1)*.8,0]}><mesh><sphereGeometry args={[.2,18,18]}/><meshStandardMaterial color={i===1?'#75e7ff':'#ceff43'} emissive={i===1?'#167a90':'#557000'} emissiveIntensity={1}/></mesh><Html center><span className="skill">{x}</span></Html></Float>)}</group>}
function Room({onLaptop}:{onLaptop:()=>void}){return <><color attach="background" args={['#070a10']}/><fog attach="fog" args={['#070a10',5,16]}/><ambientLight intensity={.45}/><pointLight position={[-3,4,2]} intensity={13} color="#ffb16a" distance={8}/><pointLight position={[3,3,-2]} intensity={8} color="#59dff8" distance={8}/><mesh position={[0,-.25,0]}><boxGeometry args={[7,.32,3.4]}/><meshStandardMaterial color="#202b29" metalness={.8} roughness={.35}/></mesh><mesh position={[0,-.55,0]}><boxGeometry args={[8,.3,5]}/><meshStandardMaterial color="#081116" metalness={.7}/></mesh><Laptop onClick={onLaptop}/><Phone/><Notebook/><Hologram/><Skills/><ContactShadows position={[0,-.72,0]} opacity={.75} scale={11} blur={2.5}/><Stars radius={40} depth={25} count={900} factor={2} saturation={0}/><Camera/></>}
export default function Studio({onLaptop}:{onLaptop:()=>void}){return <Canvas dpr={[1,1.5]} gl={{antialias:false,powerPreference:'high-performance'}}><PerspectiveCamera makeDefault position={[0,2.2,9]} fov={43}/><Room onLaptop={onLaptop}/><EffectComposer multisampling={0}><Bloom intensity={1.2} luminanceThreshold={.5} mipmapBlur/><Noise opacity={.035}/><Vignette eskil={false} offset={.25} darkness={.8}/></EffectComposer></Canvas>}
